# Generated by Django 3.0 on 2019-12-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191207_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrucel',
        ),
    ]
