# Generated by Django 3.0 on 2019-12-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_carrucel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrucel',
        ),
    ]
