# Generated by Django 3.0 on 2019-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_carrucel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrucel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen N°')),
                ('empresa', models.CharField(max_length=90, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Carrucel',
                'verbose_name_plural': 'Carruceles',
            },
        ),
    ]
