# Generated by Django 3.0 on 2019-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_carrucel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrucel',
            name='empresa',
            field=models.CharField(max_length=90, null=True, verbose_name='Empesa N°1'),
        ),
        migrations.AlterField(
            model_name='carrucel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen N°1'),
        ),
    ]
