# Generated by Django 3.0 on 2019-12-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191207_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrucel',
        ),
    ]
