# Generated by Django 3.0 on 2019-12-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(default='SOME STRING', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(max_length=100, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
