# Generated by Django 3.0 on 2019-12-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191209_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
    ]
