# Generated by Django 3.0 on 2019-12-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_info_contactos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_contactos',
            options={'verbose_name': 'info Contacto', 'verbose_name_plural': 'Info Contactos'},
        ),
    ]
