# Generated by Django 3.0 on 2019-12-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191209_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='info_contactos',
            options={'verbose_name': 'info_Contacto', 'verbose_name_plural': 'Info Contactos'},
        ),
    ]
