# Generated by Django 3.0 on 2019-12-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191209_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_contactos',
            name='categoria',
        ),
    ]
