# Generated by Django 3.0 on 2019-12-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191209_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Web',
        ),
    ]
