# Generated by Django 3.0 on 2019-12-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_delete_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(default='SOME STRING', max_length=110, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.URLField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Slug'),
        ),
    ]
