# Generated by Django 3.0 on 2019-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191212_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=110, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug'),
        ),
    ]
