# Generated by Django 3.0 on 2019-12-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_noticias_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='noticias',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
