# Generated by Django 3.0 on 2019-12-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191212_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('Inicio', models.URLField(blank=True, max_length=255, verbose_name='Inicio')),
                ('TituloInicio', models.CharField(max_length=90, verbose_name='Titulo Inicio')),
                ('Acercade', models.URLField(blank=True, max_length=255, verbose_name='Acerca de')),
                ('TituloAcercade', models.CharField(max_length=90, verbose_name='Titulo Acerca de')),
                ('Productos', models.URLField(blank=True, max_length=255, verbose_name='Productos')),
                ('TituloProductos', models.CharField(max_length=90, verbose_name='Titulo Productos')),
                ('Clientes', models.URLField(blank=True, max_length=255, verbose_name='Clientes')),
                ('TituloClientes', models.CharField(max_length=90, verbose_name='Titulo Clientes')),
                ('Contactos', models.URLField(blank=True, max_length=255, verbose_name='Contactos')),
                ('TituloContactos', models.CharField(max_length=90, verbose_name='Titulo Contactos')),
            ],
            options={
                'verbose_name': 'Imagen y titulo',
                'verbose_name_plural': 'Imagenes titulos',
            },
        ),
    ]
