# Generated by Django 3.0 on 2019-12-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_fondos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fondos',
        ),
    ]
